### ISSUE TITLE
Keep keyboard showing android

### ISSUE THREAD

**Issue by song50119** [prscX/react-native-app-tour#11]

**Comment by prscX** [comment]
Thanks @pvsong for raising your concern.

This library is a ReactNative wrapper around these native libraries. Keyboard is handle by native implementation of [KeepSafe/TapTargetView](https://github.com/KeepSafe/TapTargetView). 

[KeepSafe/TapTargetView](https://github.com/KeepSafe/TapTargetView) does not have any prop in order to allow target to have animation while keyboard is displayed. It automatically hides the keyboard while iOS native library is not hiding the keyboard.

Can you please raise your concerns to [KeepSafe/TapTargetView](https://github.com/KeepSafe/TapTargetView). 

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @pvsong: I am closing the issue since no fix can be applied to this library in order to solve the issue.

Please feel free to raise your concerns to [KeepSafe/TapTargetView](https://github.com/KeepSafe/TapTargetView)

Thanks
</ Pranav >
