### ISSUE TITLE
build steps are ugly

### ISSUE THREAD

**Issue by j-mendez** [prscX/react-native-app-tour#20]
This could be a good package if it had simpler steps as in only needing to react-native link after installation.

**Comment by prscX** [comment]
Thanks @jeffreymendez1993 for raising your concern. I too share the same thoughts and completely agree with your view.

Complication is when the RN Native Module library is dependent on native iOS Swift library. Previous we have done a detailed R&D but couldn't get the right solution, however @congnguyen91 has shared few scripts in order to make it simpler and coming days I have plans to do some R&D around the same. I will keep you posted about the progress.

For now, I would request to please follow `README` installation video shared/created by @Noitidart, hope it will reduce your pain a little. 

Thanks
</ Pranav >

**Comment by Noitidart** [comment]
I will try to make a nice and clean step by step list to go with that video. :)

**Comment by prscX** [comment]
Thanks a lot @Noitidart for the effort, meantime I will also perform some R&D around how we can make the installation steps simpler for iOS platform.

Thanks
</ Pranav >

**Comment by Noitidart** [comment]
Thank you Pranav!! :)
